# Generated by Django 4.0.6 on 2022-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_description_game_genre_game_name_game_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
